[build]
  publish = "frontend/build"
  functions = "netlify/functions"
  command = "cd frontend && npm install --legacy-peer-deps && npm run build"

# Plugin to install dependencies for Netlify Functions
[[plugins]]
  package = "@netlify/plugin-functions-install-core"

[build.environment]
  NODE_VERSION = "20"
  NODE_OPTIONS = "--max-old-space-size=4096"
  NPM_FLAGS = "--legacy-peer-deps"
  CI = "false"
  SKIP_PREFLIGHT_CHECK = "true"
  DISABLE_ESLINT_PLUGIN = "true"
  ESLINT_NO_DEV_ERRORS = "true"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200

[[redirects]]
  from = "/ws"
  to = "/.netlify/functions/websocket"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.processing]
  skip_processing = false

[build.processing.css]
  bundle = true
  minify = true

[build.processing.js]
  bundle = true
  minify = true

[build.processing.html]
  pretty_urls = true

[functions]
  directory = "netlify/functions"