[build]
  base = "frontend"
  publish = "build"
  command = "npm install && npm run build"

[build.environment]
  NODE_VERSION = "20"
  NODE_OPTIONS = "--max-old-space-size=4096"
  GENERATE_SOURCEMAP = "false"
  CI = "false"
  DISABLE_ESLINT_PLUGIN = "true"
  REACT_APP_API_URL = "https://d0e9f5c3a9a0.ngrok-free.app"
  REACT_APP_SOCKET_URL = "https://d0e9f5c3a9a0.ngrok-free.app"

# Build optimizations - disable some processing to reduce memory usage
[build.processing]
  skip_processing = true

# Headers for SPA routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "no-referrer"
    X-Content-Type-Options = "nosniff"

# Cache optimization for static assets
[[headers]]
  for = "/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"